workflows:
  ios-fastlane:
    name: Integration Fastlane iOS
    instance_type: mac_mini_m1
    environment:
      groups:
        - ios_credentials
        - fastlane
      xcode: default
      cocoapods: default
    scripts:
      # - gem install bundler:2.2.27
      - bundle install
      - bundle exec fastlane beta
    artifacts:
      - ./*.ipa
      - ./*.dSYM.zip        